### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by meletisf** [oliwierptak/popo#10]
Hello, 

First of all i would like to begin by saying how happy i am that someone loves and appreciates POPOs :) 

I came across this package randomly and i would like to use it in a PHP 8 project but it seems like the composer.json locks it on 7.4. Have you tested in on 8?

Thanks in advance!

**Comment by oliwierptak** [comment]
Hello,

Thank you for your message.

Version 4.x has been released and it's for PHP version 8.x: https://github.com/oliwierptak/popo/tree/4.0.0

But if possible, I would suggest to upgrade to version 5.
However, it uses  Yaml instead of JSON schema, which is much simpler and offers more features, also no need to deal with templates anymore.
